config/routes.rb
Jci::Application.routes.draw do
  devise_for :admins#, :skip => :registrations

devise_scope :admin do
  get "/login" => "devise/sessions#new"
end

devise_scope :admin do
  delete "/logout" => "devise/sessions#destroy"
end

unauthenticated :admin do
  root :to => 'home#index'
end

  get "home/index"

  resources :posts

resources :home do
    collection do
      get :cadastrar
      get :logar
      get :admin
      get :contato
      get :sobre
    end
  end

  resources :voluntario_pessoa_juridicas do
    resources :historicos
     collection do
      get :buscar
      get :editarmeucadastro
      get :vermeucadastro
      get :visualizado_pj
      get :buscarHistorico
      get :buscarGeral
      get :buscarArray
    end
  end

  resources :entidades do
    resources :historicos 
    collection do
      get :buscar
      get :buscarArray
      get :editarmeucadastro
      get :vermeucadastro
      get :several
      get :aprovado
      get :visualizado_ent
      get :busca_publico_ent
      get :busca_por_atuacao
      get :busca_por_apoio
      get :buscarHistorico
      get :cruzar_pf_ent
    end
  end

  resources :voluntario_pessoa_fisicas do
    resources :historicos
    collection do
      get :buscar
      get :editarmeucadastro
      get :vermeucadastro
      get :visualizado_pf   
      get :busca_disponibilidade_horario
      get :busca_por_afinidade
      get :busca_por_disponibilidade
      get :busca_experiencia
      get :busca_atuacao
      get :buscarHistorico
      get :buscarGeral
      get :cruzar_pf_ent
    end
  end

  resources :senhorjcis do
    collection do
      get :index
      get :inbox
      get :admin
      get :pendencias
      get :novoAdministrador
      get :adicionarAdministrador
    end
  end

match 'entidades/:entidade_id/historicos/:id(.:format)' => 'historicos#destroy_ent', :as => :destroy_ent
match 'voluntario_pessoa_fisicas/:voluntario_pessoa_fisica_id/historicos/:id(.:format)' => 'historicos#destroy_pf', :as => :destroy_pf
match 'voluntario_pessoa_juridicas/:voluntario_pessoa_juridica_id/historicos/:id(.:format)' => 'historicos#destroy_pj', :as => :destroy_pj

  get "entidades/list"

  root :to => 'home#index'  

  match '/' => 'home#index', :as => :home

end

app/controllers/senhorjcis_controller.rb
class SenhorjcisController < ApplicationController
#  before_filter :authorize
before_filter :authenticate_admin!

  def admin
    render 'inbox'
  end

  def novoAdministrador
    render 'novoAdministrador'
  end

  def adicionarAdministrador
    login = params[:login]
    sql = "insert into admins (email, created_at, updated_at) VALUES ('"+login+"', now(), now())"
    ActiveRecord::Base.connection.execute(sql)
    redirect_to inbox_senhorjcis_path
  end

  def pendencias
    @entidades = Entidade.where("aprovado_ent = ?", false).paginate(:page => params[:page], :per_page => 10)
  end

  #TODO: querys retornando em ordem alfabetica
  def inbox
    @entidades = Entidade.where("visualizado_ent = ?", false ).order("nome_ent")
    @voluntario_pessoa_fisicas = VoluntarioPessoaFisica.where("visuzalizado_pf = ?", false).order("nome_pf")
    @voluntario_pessoa_juridicas = VoluntarioPessoaJuridica.where("visualizado_pj = ?", false).order("razao_social_pj")
 end
end
# canaldevoluntariosjci@gmail.com
# senhorjci2012

app/views/senhorjcis/_menu.html.erb
<div id="menu_admin">   
    <ul>
        <li><%= link_to 'Inbox', { :controller => "senhorjcis", :action => "inbox" } %></li>
        <li><%= link_to 'Pendências', { :controller => "senhorjcis", :action => "pendencias" } %></li>
        <li><%= link_to 'Entidades', entidades_path %></li>
        <li><%= link_to 'Voluntários Pessoa Física', voluntario_pessoa_fisicas_path %></li>
        <li><%= link_to 'Voluntários Pessoa Jurídica', voluntario_pessoa_juridicas_path %></li>
        <li><%= link_to 'Notícias', posts_path %></li>
        <li><%= link_to 'Novo Administrador', :controller => "senhorjcis", :action => "novoAdministrador" %></li>
        <li><%= link_to 'Sair', destroy_admin_session_path, :method => :delete %></li>

    </ul>
</div>

app/views/senhorjcis/inbox.html.erb
<!-- render abaixo abre uma div que está sendo fechada na ultima linha dessa pagina -->
<%= render 'senhorjcis/menu' %>
<div id="corpo">

<p id="notice"><%= notice %></p>

<table border=1>
  <th style='width:100px'> Tipo </th>
  <th> Nome </th> 
<% @entidades.each do |entidade| %>
  <tr>
    <td>Entidade</td>
    <td><%= link_to entidade.nome_ent, {:controller => "entidades", :action => "visualizado_ent", :id => entidade.id } %></td>
 </tr>
<% end %>

<% @voluntario_pessoa_fisicas.each do |voluntario_pessoa_fisica| %>
  <tr>
    <td>Pessoa Física</td>
    <td><%= link_to voluntario_pessoa_fisica.nome_pf, {:controller => "voluntario_pessoa_fisicas", :action => "visualizado_pf", :id => voluntario_pessoa_fisica.id } %></td>
 </tr>
<% end %>

<% @voluntario_pessoa_juridicas.each do |voluntario_pessoa_juridica| %>
  <tr>
    <td>Pessoa Jurídica</td>
    <td><%= link_to voluntario_pessoa_juridica.razao_social_pj, { :controller => "voluntario_pessoa_juridicas", :action => "visualizado_pj", :id => voluntario_pessoa_juridica.id }%></td>
 </tr>
<% end %>
</table>


</div>

app/views/senhorjcis/novoAdministrador.html.erb
<%= render 'senhorjcis/menu' %>
<div id="corpo">

<p id="notice"><%= notice %></p>


<h3>Novo Administrador</h3>
<%= form_tag({:controller => 'senhorjcis', :action => 'adicionarAdministrador'}, :method => 'get') do %>
      <%= text_field_tag :login %>
      <%= submit_tag "Adicionar", :class => "botao_verde" %> 
<% end  %>

</div>

app/views/senhorjcis/pendencias.html.erb
<!-- render abaixo abre uma div que está sendo fechada na ultima linha dessa pagina -->
<%= render 'senhorjcis/menu' %>
<div id="corpo">

<table border=1>
  <th style='width:100px'> Tipo </th>
  <th> Nome </th> 
<% @entidades.each do |entidade| %>
  <tr>
    <td>Entidade</td>
    <td><%= link_to entidade.nome_ent, {:controller => "entidades", :action => "visualizado_ent", :id => entidade.id } %></td>
 </tr>
<% end %>
</table>
     <%= will_paginate @entidades %>
</div>