config/routes.rb
Jci::Application.routes.draw do
  devise_for :admins#, :skip => :registrations

devise_scope :admin do
  get "/login" => "devise/sessions#new"
end

devise_scope :admin do
  delete "/logout" => "devise/sessions#destroy"
end

unauthenticated :admin do
  root :to => 'home#index'
end

  get "home/index"

  resources :posts

resources :home do
    collection do
      get :cadastrar
      get :logar
      get :admin
      get :contato
      get :sobre
    end
  end

  resources :voluntario_pessoa_juridicas do
    resources :historicos
     collection do
      get :buscar
      get :editarmeucadastro
      get :vermeucadastro
      get :visualizado_pj
      get :buscarHistorico
      get :buscarGeral
      get :buscarArray
    end
  end

  resources :entidades do
    resources :historicos 
    collection do
      get :buscar
      get :buscarArray
      get :editarmeucadastro
      get :vermeucadastro
      get :several
      get :aprovado
      get :visualizado_ent
      get :busca_publico_ent
      get :busca_por_atuacao
      get :busca_por_apoio
      get :buscarHistorico
      get :cruzar_pf_ent
    end
  end

  resources :voluntario_pessoa_fisicas do
    resources :historicos
    collection do
      get :buscar
      get :editarmeucadastro
      get :vermeucadastro
      get :visualizado_pf   
      get :busca_disponibilidade_horario
      get :busca_por_afinidade
      get :busca_por_disponibilidade
      get :busca_experiencia
      get :busca_atuacao
      get :buscarHistorico
      get :buscarGeral
      get :cruzar_pf_ent
    end
  end

  resources :senhorjcis do
    collection do
      get :index
      get :inbox
      get :admin
      get :pendencias
      get :novoAdministrador
      get :adicionarAdministrador
    end
  end

match 'entidades/:entidade_id/historicos/:id(.:format)' => 'historicos#destroy_ent', :as => :destroy_ent
match 'voluntario_pessoa_fisicas/:voluntario_pessoa_fisica_id/historicos/:id(.:format)' => 'historicos#destroy_pf', :as => :destroy_pf
match 'voluntario_pessoa_juridicas/:voluntario_pessoa_juridica_id/historicos/:id(.:format)' => 'historicos#destroy_pj', :as => :destroy_pj

  get "entidades/list"

  root :to => 'home#index'  

  match '/' => 'home#index', :as => :home

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.paginate(:order => 'created_at DESC', :page => params[:page], :per_page => 1)
  end
	
  def admin
    render 'admin'
  end

  def logar
    render 'logar'
  end

  def cadastrar
    render 'cadastrar'
  end

  def contato
    render 'contato'
  end

  def sobre
    render 'sobre'
  end
end

#FIX: excluir metodos nao usados em todos os controllers

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/admin.html.erb
<%= link_to "Voluntario Pessoa Fisica", voluntario_pessoa_fisicas_path %><br />
<%= link_to "Voluntario Pessoa Juridica", voluntario_pessoa_juridicas_path %><br />
<%= link_to "Entidade", entidades_path %><br />
<%= link_to "Posts", posts_path %><br />
<%= link_to 'Inbox', {:action => 'inbox'}%><br />
<%= link_to 'Pendencias', {:action => 'pendencias'}%><br />

app/views/home/cadastrar.html.erb
<div id="corpo-site">
    
    <div id="botoes">
        <h1> Desejo me cadastrar como: </h1>
    <%= link_to "Voluntário Pessoa Física", new_voluntario_pessoa_fisica_path, :class => "botao" %><br />
    <%= link_to "Voluntário Pessoa Jurídica", new_voluntario_pessoa_juridica_path, :class => "botao" %><br />
    <%= link_to "Entidade", new_entidade_path, :class => "botao" %><br />
</div>
</div>

app/views/home/contato.html.erb
<div id="corpo-site">
<iframe frameborder="0" height="700" marginheight="0" marginwidth="0" src="https://docs.google.com/spreadsheet/embeddedform?formkey=dGxFSlJHN3Vub3k1c1lWc0FMZURVWmc6MQ" width="100%"></iframe>
</div>

app/views/home/index.html.erb
<div id="main">
    <div id="left">
        <%= image_tag("jcipeople.png", :alt => "JCI People") %>
        <h2>Junte-se a nós, seja um voluntário e participe da maior associacão mundial de jovens que buscam no aprimoramento individual, bases para o desenvolvimento de suas comunidades.</h2>
    </div>
    <div id="right">
        <%= render :template => 'posts/noticias' %>
        </div>
    <div style="clear: both"></div>
</div>

app/views/home/logar.html.erb
<div id="corpo-site" style="text-align:center">
<h2>Sou uma Entidade</h2>
<%= form_tag({:controller => 'entidades', :action => 'buscar'}, :method => 'get') do %>
  <%= text_field_tag :cnpj_ent, nil, :class => 'cnpj'%>
      <%= submit_tag "Ver meus dados", :class => "botao_verde" %> 
<% end  %>
<br />
<h2>Sou uma Pessoa Física</h2>
<%= form_tag({:controller => 'voluntario_pessoa_fisicas', :action => 'buscar'}, :method => 'get') do %>
  <%= text_field_tag :cpf, nil, :class => 'cpf'%>
      <%= submit_tag "Ver meus dados", :class => "botao_verde" %> 
<% end  %>
<br />
<h2>Sou uma Pessoa Jurídica</h2>
<%= form_tag({:controller => 'voluntario_pessoa_juridicas', :action => 'buscar'}, :method => 'get') do %>
  <%= text_field_tag :cnpj_pj, nil, :class => 'cnpj' %>
      <%= submit_tag "Ver meus dados", :class => "botao_verde" %> 
<% end  %>
</div>

app/views/home/sobre.html.erb
<div id="corpo-site" style="text-align:justify;">
<h1>O que é JCI</h1>
<p>A JCI - Junior Chamber International é uma organização mundial que oferece oportunidades de desenvolvimento que preparam as pessoas jovens para criar mudanças positivas. É formada por mais de 200 mil voluntários de 18 a 40 anos em 115 países, jovens cidadãos ativos dedicados a criar mudanças positivas em suas comunidades. Os membros da JCI assumem a responsabilidade por suas comunidades identificando problemas e criando soluções. Buscando também o desenvolvimento contínuo de seus membros por meio de projetos e capacitação, os membros da JCI vivem a missão de criar mudanças positivas e o slogan Be Better, Ser Melhor, para fazer cada vez mais pela comunidade.</p>
<br />
<h1>Áreas de Atuação</h1>
<p>A JCI atua nas áreas comunitária, individual, internacional e negócios. A área comunitária é a principal área da organização, tendo como objetivo realizar projetos de impacto que melhorem a comunidade de forma sustentável. A área individual visa oferecer oportunidades de desenvolvimento e capacitação por meio de  experiência em projetos, relacionamento interpessoal e capacitação. A área internacional visa formar a consciência de cidadania global por meio de troca de experiências entre diferentes culturas para desenvolver pessoas melhores. E a área de negócios se relaciona a empreendedorismo e a formação de negócios e relações comerciais que contribuam para o desenvolvimento do pais e na construção de um melhor lugar para ser viver.</p>
<br />
<h1>Fundação</h1>
<p>A JCI foi fundada em Saint Louis em 1915 por Henry Giessenbier tendo como pilares ação de verdade, não apenas conversa, melhorar a comunidade e reuniões verdadeiramente interessantes. A JCI foi fundada com a consciência de que "o adequado treinamento cívico das pessoas jovens fará com que elas tenham uma influencia decisiva na solução justa dos problemas da humanidade". A base da JCI é a cidadania ativa e a criação da mudança positiva. Está em fazer uso de seu poder e talento para melhorar o mundo, para resolver problemas em sua comunidade e impactar positivamente a vida dos outros.</p>
<br />
<h1>Ex-membros</h1>
<p>Devido a esse espírito de serviço à comunidade, a JCI tem entre seus ex-membros John Kennedy, Charles Lindbergh, Howard Hughes, George Bush, Gerald Ford, Richard Nixon, Bill Clinton, Al Gore, Jacques Chirac, Taro Aso e Kofi Annan.</p>
<br />
<h1>Missão</h1>
<p>"Proporcionar oportunidades de desenvolvimento que preparem as pessoas jovens para criar mudanças positivas"</p>
<br />
<h1>Visão</h1>
<p style="text-align: center; font-size: 23px; font-weight: bold; font-style: oblique; ">"Ser a principal rede mundial de jovens cidadãos ativos"</p>
<br />
<h1>Carta de Princípios</h1>
<p>Nós acreditamos,
Que a fé em Deus dá sentido e finalidade à vida
Que a fraternidade entre os homens transcende a soberania das nações
Que a justiça econômica pode ser melhor obtida por homens livres através da livre iniciativa
Que governos devem ser de leis mais do que de homens
Que o maior tesouro da Terra está na personalidade humana
E que servir a humanidade é a melhor obra de uma vida</p>

<p>A Carta de Princípios foi criada por William Brownfield em 1946 para descrever o espírito de serviço à humanidade dos membros da JCI.</p>

<p>Que a fé em Deus dá sentido e finalidade à vida: "Os membros da JCI, vindos das mais diversas religiões, estão unidos por laços comuns de fé, de que os homens vivem pela vontade de Deus, que os planos de Deus para os homens são bons e que a vida vale a pena ser vivida em harmonia com o plano eterno de Deus."</p>

<p>Que a fraternidade entre os homens transcende a soberania das nações: "As fronteiras feitas pelo homem foram delineadas e redelineadas, separando a raça humana em muitas nações. Mas através desta divisão não natural houve intercâmbios na arte, ciência, comércio e religião que evidencia a fraternidade universal dos homens; prova de que o homem e não as divisões territoriais é que possuem o verdadeiro valor."</p>

<p>Que a justiça econômica pode ser melhor obtida por homens livres, através da livre iniciativa: "Onde a melhoria da economia foi mais significante, os homens tem estado livres para perseguir seus sonhos de fazer fortunas fazendo algo nunca tentado antes, ou por fazê-lo melhor. O sistema de auto-desenvolvimento através da iniciativa privada pode ser adaptado com variações para ajustar-se às condições locais em qualquer parte do mundo."</p>

<p>Que os governos devem ser de leis mais que de homens: "Numa sociedade livre a lei é fundamental e vem do povo. É ele que detém a autoridade final."</p>

<p>Que o grande tesouro da terra está na personalidade humana: "O verdadeiro tesouro da Terra reside no coração do Homem. Existe um vasto campo de oportunidades no cultivo da personalidade humana. Não é a quantidade de anos que dá prazer à atividade, mas a qualidade na qual ela é vivida, os êxitos que alcançamos em termos de progresso da pessoa humana."</p>
<p>E que servir a humanidade é a melhor obra de uma vida: "A vida vivida sem egoísmo é mais rica, profunda e bela."</p>
<br />
<p style="text-align: center">Acesse também os sites da JCI Brasil <a href="http://www.jci.org.br">http://www.jci.org.br</a></p>
<p style="text-align: center">e da JCI Mundial <a href="http://www.jci.cc">http://www.jci.cc</a></p>
<br />
</div>