config/routes.rb
Jci::Application.routes.draw do
  devise_for :admins#, :skip => :registrations

devise_scope :admin do
  get "/login" => "devise/sessions#new"
end

devise_scope :admin do
  delete "/logout" => "devise/sessions#destroy"
end

unauthenticated :admin do
  root :to => 'home#index'
end

  get "home/index"

  resources :posts

resources :home do
    collection do
      get :cadastrar
      get :logar
      get :admin
      get :contato
      get :sobre
    end
  end

  resources :voluntario_pessoa_juridicas do
    resources :historicos
     collection do
      get :buscar
      get :editarmeucadastro
      get :vermeucadastro
      get :visualizado_pj
      get :buscarHistorico
      get :buscarGeral
      get :buscarArray
    end
  end

  resources :entidades do
    resources :historicos 
    collection do
      get :buscar
      get :buscarArray
      get :editarmeucadastro
      get :vermeucadastro
      get :several
      get :aprovado
      get :visualizado_ent
      get :busca_publico_ent
      get :busca_por_atuacao
      get :busca_por_apoio
      get :buscarHistorico
      get :cruzar_pf_ent
    end
  end

  resources :voluntario_pessoa_fisicas do
    resources :historicos
    collection do
      get :buscar
      get :editarmeucadastro
      get :vermeucadastro
      get :visualizado_pf   
      get :busca_disponibilidade_horario
      get :busca_por_afinidade
      get :busca_por_disponibilidade
      get :busca_experiencia
      get :busca_atuacao
      get :buscarHistorico
      get :buscarGeral
      get :cruzar_pf_ent
    end
  end

  resources :senhorjcis do
    collection do
      get :index
      get :inbox
      get :admin
      get :pendencias
      get :novoAdministrador
      get :adicionarAdministrador
    end
  end

match 'entidades/:entidade_id/historicos/:id(.:format)' => 'historicos#destroy_ent', :as => :destroy_ent
match 'voluntario_pessoa_fisicas/:voluntario_pessoa_fisica_id/historicos/:id(.:format)' => 'historicos#destroy_pf', :as => :destroy_pf
match 'voluntario_pessoa_juridicas/:voluntario_pessoa_juridica_id/historicos/:id(.:format)' => 'historicos#destroy_pj', :as => :destroy_pj

  get "entidades/list"

  root :to => 'home#index'  

  match '/' => 'home#index', :as => :home

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>JCI</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "jquery.maskedinput" %>
  <%= javascript_include_tag "utils" %>
  <%= csrf_meta_tag %>
</head>
<body>

  <div id="wrapper">
    <div id="header">
    

      <div id="logo">
        <%= link_to( image_tag("logo.png", :alt => "rss feed"), home_path) %> 
      </div>
      
      <div id="menu">
        <ul>
          <li><%= link_to 'Home', home_path %></li>
          <li><%= link_to 'Cadastre-se', cadastrar_home_index_path %></li>
          <li><%= link_to 'Alterar meus dados', logar_home_index_path %></li>
          <li><%= link_to 'Sobre', sobre_home_index_path %></li>
          <li><%= link_to 'Contato', contato_home_index_path%></li>
          <li><%= link_to 'Admin', inbox_senhorjcis_path %></li>   

        </ul>
      </div>

    </div>
    <%= yield %>
  </div>
</body>
</html>